version: "3.7"
services:
  app:
    image: debian:11-slim
    container_name: exp-img-bot
    restart: always
    working_dir: /go
    env_file: .env
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ./:/go
      - /etc/ssl/certs:/etc/ssl/certs/
    command: ./app_arm
