name: Deploy

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cpu: [amd64, arm32]
        include:
          - cpu: amd64
            arch: amd64
          - cpu: arm32
            arch: arm

    steps:
      - uses: actions/setup-go@v2
      - uses: actions/checkout@v2
      - name: get depend's
        run: go mod download
      
      - name: build
        env:
          arch: ${{ matrix.arch }}
        run: |
          GOOS=linux GOARCH=$arch go build -o ./bin/app_$arch ./cmd/main.go

      - name: create release
        uses: softprops/action-gh-release@v1
        with:
          files: ./bin/*
          draft: true
