name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: create release
        uses: softprops/action-gh-release@v1
        with:
          draft: true